---

# we assume that the zabbix repo files are installed
# i.e. the packages are available
#
# for centos e.g.
# http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
#
- name: install zabbix
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-agent

- name: zabbix is configured
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    backup: yes
  notify: restart zabbix
  
- name: zabbix database is present
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin
  delegate_to: "{{ zabbix.db_server }}"

- name: zabbix database user is present
  mysql_user:
    name: zabbix
    host: "{{ ansible_fqdn }}"
    password: "{{ mysqld.pwd.zabbix }}"
    priv: zabbix.*:ALL
  delegate_to: "{{ zabbix.db_server }}"

- name: zabbix seboolean
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_can_connect_zabbix
    - zabbix_can_network
    - httpd_can_network_connect_db

- name: copy custom selinux policy
  copy:
    src: zabbix_server_additions.pp 
    dest: /root/zabbix_server_additions.pp

- name: load custom selinux policy
  command: semodule -i /root/zabbix_server_additions.pp

- name: zabbix is running
  service:
    name: zabbix-server
    state: started
    enabled: true
