---

- name: open port for monitoring
  firewalld:
    zone: dmz
    port: 10050/tcp
    state: enabled
    permanent: yes
    immediate: yes
    source: "{{ item }}"
  with_items: "{{ zabbix.server }}"
