---

- name: OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: zabbix agent is installed
  package:
    name: "{{ zabbix.agent_package }}"
    state: present

- name: config dir for zabbix does exist
  notify: restart zabbix agent
  file:
    path: /etc/zabbix/zabbix_agentd.d
    state: directory

- name: zabbix agent is configured
  template:
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  with_items:
    - zabbix_agentd.conf.j2
  notify: restart zabbix agent

- name: home directory does exist
  file:
    path: /var/lib/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0750

- name: zabbix include dir
  file:
    path: "{{ zabbix.cfg.Include }}"
    state: directory

- name: zabbix agent is running
  service:
    name: zabbix-agent
    state: started
    enabled: yes

